#!/bin/sh
# commitmonkey hook


COMMIT_MSG_FILE=$1

if [ -z "$COMMIT_MSG_FILE" ]; then
  echo "commitmonkey: No commit message file provided. Exiting."
  exit 1
fi

MESSAGE="$(cat $COMMIT_MSG_FILE)"
ROAST=$(__COMMITMONKEY_HOOK_PATH__ roast "$MESSAGE")
echo "$ROAST" > $COMMIT_MSG_FILE